# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'

target 'MajorForum' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MajorForum

pod 'Masonry'
pod 'YYModel'
pod 'YYWebImage'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'JSExtension'
pod 'AlicloudMAN'

  target 'MajorForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MajorForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
