# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MajorForum' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MajorForum

pod 'Masonry'
pod 'YYModel'
pod 'YYWebImage'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD'

  target 'MajorForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MajorForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
